name: SCA - OWASP Dependency Check

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Install OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.1.2/dependency-check-8.1.2-release.zip
          unzip dependency-check-8.1.2-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh
          mkdir -p dependency-check-report

      - name: Run OWASP Dependency Check
        run: |
          dependency-check/dependency-check/bin/dependency-check.sh --project "Express.js Application" --scan . --format "ALL" --out dependency-check-report

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@master
        with:
           name: Dependency Check report
           path: ${{github.workspace}}/app/build/reports/dependency-check/dependency-check-report.html
