name: SCA - OWASP Dependency Check

on:
  push:
    branches:
      - master
  pull_request: {}
  workflow_dispatch:

jobs:
  depchecktest:
    runs-on: ubuntu-latest
    name: depecheck_test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project with Maven
        run: mvn clean install
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Express.js Application'
          path: '.'
          format: 'ALL'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Depcheck results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports


  # dependency-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20'

  #     - name: Install npm dependencies
  #       run: npm install

  #     - name: Install OWASP Dependency Check
  #       run: |
  #         wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.1.2/dependency-check-8.1.2-release.zip
  #         unzip dependency-check-8.1.2-release.zip -d dependency-check
  #         chmod +x dependency-check/dependency-check/bin/dependency-check.sh
  #         mkdir -p dependency-check-report

  #     - name: Run OWASP Dependency Check
  #       run: |
  #         dependency-check/dependency-check/bin/dependency-check.sh --project "Express.js Application" --scan . --format "ALL" --out dependency-check-report

  #     - name: Upload Dependency Check Report
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: dependency-check-report
  #         path: dependency-check-report
